#!/bin/sh
echo 
echo "====================Start====================="
PROJECT_PATH=./USER
BUILD_TOOL=/D/UV4/UV4.exe

echo "\033[33m PROJECT_PATH:\033[0m $PROJECT_PATH"
echo "\033[33m BUILD_TOOL:\033[0m $BUILD_TOOL"
echo 

cd $PROJECT_PATH
echo "\033[33m Note:\033[0m Path is $(pwd) now..."
PROJECT_NAME=$(ls | grep .uvprojx)

if [ $PROJECT_NAME ];then
echo "\033[33m Note:\033[0m Find project name is $PROJECT_NAME!"
else
echo "\033[31m Error:\033[0mCan not find project, Please check Path !"
exit
fi

echo "\033[32m Install:\033[0m $PROJECT_NAME "
rm ./Install_Output.txt
touch ./Install_Output.txt

$BUILD_TOOL -f $PROJECT_NAME -o ./Install_Output.txt -j0

cat ./Install_Output.txt | perl -pe 's/(warning)|(error)|(Error)|(Warning)/\e[1;33m$1\e[0m\e[1;33m$2\e[0m\e[1;31m$3\e[0m\e[1;31m$4\e[0m/g' 
echo "=====================End====================="
echo 
